import { DuvetRequest } from "../models/DuvetRequest";
import { mergeDefaultWithMissingItems } from "../../utils/mergeDefaultWithMissingItems";
import { extendObject } from "../../utils/extendObject";
import { DuvetExport } from "../models/DuvetExport";
import { MaybeFunction, Middleware } from "../models/Middleware";
import { getFromFnOrValue } from "../../utils/getFromFnOrValue";
import { DuvetEndpoint } from "../models/DuvetEndpoint";
import { HandlerBuilder } from "../models/HandlerBuilder";
import { ConfigurableHandler } from "../models/ConfigurableHandler";
import { Extend } from "../../utils/types/Extend";
import { NotKeyOf } from "../../utils/types/NotKeyOf";
import { DefineEndpointFunctionArgs } from "../models/DefineEndpointFunction";
import { ValidatorArray } from "../models/Validator";
import { extractParts } from "./extractParts";
import { wrapHandlerWithValidationLayer } from "./handlerWithValidators";

//TODO: Add more information and examples on how to use the class
/**
 * The main class that is used to define endpoints and build a router
 */
export class DuvetEndpointBuilder<
  Context extends { global: GlobalContext },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  Config extends Record<string, any>,
  DefaultConfig,
  GlobalContext,
> {
  /**
   * Creates a new DuvetEndpointBuilder object. This is the starting point for defining endpoints.
   * @returns A new DuvetEndpointBuilder instance with a global context object.
   */
  public static new<GlobalContext>() {
    type Context = {
      global: GlobalContext;
    };

    type Config = {};

    const handlerBuilder: HandlerBuilder<GlobalContext, Context, Config> = {
      buildConfigurableHandler: <
        NewContext extends Context,
        NewConfig extends Config,
      >(
        innerHandler: ConfigurableHandler<NewContext, NewConfig>,
      ) =>
        innerHandler as ConfigurableHandler<
          { global: GlobalContext },
          NewConfig
        >,
    };

    return new DuvetEndpointBuilder<Context, Config, {}, GlobalContext>(
      {},
      handlerBuilder,
    );
  }

  private defaultConfig: DefaultConfig;

  /**
   * Builds a new handler with all the previous middleware applied to it.
   */
  private handlerBuilder: HandlerBuilder<GlobalContext, Context, Config>;

  private constructor(
    defaultConfig: DefaultConfig,
    handlerBuilder: HandlerBuilder<GlobalContext, Context, Config>,
  ) {
    this.defaultConfig = defaultConfig;
    this.handlerBuilder = handlerBuilder;
  }

  /**
   * Extends the default config object. Takes a partial object to extend the default config object with.
   * @param extension A partial object to extend the default config object with.
   * @returns A new DuvetEndpointBuilder instance with the new default config object.
   */
  extendConfig<DefaultConfigExtension extends Partial<Config>>(
    extension: DefaultConfigExtension,
  ) {
    return new DuvetEndpointBuilder<
      Context,
      Config,
      DefaultConfig & DefaultConfigExtension,
      GlobalContext
    >(extendObject(this.defaultConfig, extension), this.handlerBuilder);
  }

  /**
   * Creates a new DuvetEndpointBuilder with the middleware added.
   * @param middleware The middleware to extend the DuvetEndpointBuilder instance with
   * @returns A new DuvetEndpointBuilder instance with the middleware added.
   */
  addMiddleware<Name extends string, ContextExt, ConfigExt>(
    middleware: Middleware<
      NotKeyOf<Name, Config>,
      ConfigExt,
      ContextExt,
      GlobalContext
    >,
  ) {
    // TODO: Clean this function to be more readable
    // Create a new handler builder which wraps the

    const newHandlerBuilder: HandlerBuilder<
      GlobalContext,
      Extend<Context, ContextExt, Name>,
      Extend<Config, ConfigExt, Name>
    > = {
      /**
       * @param innermostHandler The handler that this middleware will wrap.
       * @returns A new handler which passes the inner handler into it.
       */
      buildConfigurableHandler: <
        NewContext extends Extend<Context, ContextExt, Name>,
        NewConfig extends Extend<Config, ConfigExt, Name>,
      >(
        innermostHandler: ConfigurableHandler<NewContext, NewConfig>,
      ) => {
        // Builds a handler using the previous handler builder to wrap the innermost handler.
        const wrappedInnerHandler =
          this.handlerBuilder.buildConfigurableHandler<NewContext, NewConfig>(
            innermostHandler,
          );

        // Returns a new handler that wraps the handler generated by the previous handler builder.
        return (
          request: DuvetRequest,
          context: { global: GlobalContext },
          config: NewConfig,
        ) =>
          middleware.handler(
            request,
            // Next function simply extends the context object with the extension object and calls the inner handler.
            // eslint-disable-next-line no-type-assertion/no-type-assertion
            ((extension?: ContextExt) => {
              if (extension)
                (context as Record<Name, ContextExt>)[middleware.name] =
                  extension;
              return wrappedInnerHandler(request, context, config);
            }) as MaybeFunction<ContextExt>,
            config[middleware.name],
            context.global,
          );
      },
    };

    // Creates a new DuvetEndpointBuilder object with the new handler builder.
    return new DuvetEndpointBuilder<
      Extend<Context, ContextExt, Name>,
      Extend<Config, ConfigExt, Name>,
      DefaultConfig,
      GlobalContext
    >(this.defaultConfig, newHandlerBuilder);
  }

  /**
   * Overrides the config object with a new one. This can be a partial object or a function that takes the current config object and returns a new one.
   * @param newConfig A new config object or a function that takes the current config object and returns a new one.
   * @returns A new DuvetEndpointBuilder instance with the new config object.
   */
  setConfig<NewDefaultConfig extends Partial<Config>>(
    newConfig: ((config: DefaultConfig) => NewDefaultConfig) | NewDefaultConfig,
  ) {
    const resolvedNewConfig = getFromFnOrValue(newConfig, this.defaultConfig);

    return new DuvetEndpointBuilder<
      Context,
      Config,
      NewDefaultConfig,
      GlobalContext
    >(resolvedNewConfig, this.handlerBuilder);
  }

  defineEndpoint<Validators extends ValidatorArray>(
    ...args: DefineEndpointFunctionArgs<
      Context,
      GlobalContext,
      Config,
      DefaultConfig,
      Validators
    >
  ): DuvetExport<DuvetEndpoint<GlobalContext, Config>> {
    const { config, validators, handler } = extractParts(...args);

    // Merges the config from the user with the default config.
    const mergedConfig = mergeDefaultWithMissingItems<Config, DefaultConfig>(
      this.defaultConfig,
      config,
    );

    const flattenedValidators = validators.flatMap((validator) => validator);

    const handlerWithMiddleware = this.handlerBuilder.buildConfigurableHandler(
      wrapHandlerWithValidationLayer(handler, flattenedValidators),
    );

    return {
      builtByDuvet: true,
      data: {
        config: mergedConfig,
        handler: (request, context) =>
          handlerWithMiddleware(request, context, mergedConfig),
        exportType: "DuvetEndpoint",
      },
    };
  }
}
